arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart # Este es solo el nombre del archivo
output-class: AppLocalizations
output-dir: lib/generated/l10n # Especificamos explícitamente dónde se generarán los archivos